/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.edu.tsinghua.iotdb.jdbc.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TSFetchMetadataResp implements org.apache.thrift.TBase<TSFetchMetadataResp, TSFetchMetadataResp._Fields>, java.io.Serializable, Cloneable, Comparable<TSFetchMetadataResp> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TSFetchMetadataResp");

  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField METADATA_IN_JSON_FIELD_DESC = new org.apache.thrift.protocol.TField("metadataInJson", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField DELTA_OBJECT_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("deltaObjectMap", org.apache.thrift.protocol.TType.MAP, (short)3);
  private static final org.apache.thrift.protocol.TField DATA_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("dataType", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField ALL_COLUMNS_FIELD_DESC = new org.apache.thrift.protocol.TField("allColumns", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField SHOW_TIMESERIES_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("showTimeseriesList", org.apache.thrift.protocol.TType.LIST, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TSFetchMetadataRespStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TSFetchMetadataRespTupleSchemeFactory());
  }

  public TS_Status status; // required
  public String metadataInJson; // optional
  public Map<String,List<String>> deltaObjectMap; // optional
  public String dataType; // optional
  public List<String> allColumns; // optional
  public List<List<String>> showTimeseriesList; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STATUS((short)1, "status"),
    METADATA_IN_JSON((short)2, "metadataInJson"),
    DELTA_OBJECT_MAP((short)3, "deltaObjectMap"),
    DATA_TYPE((short)4, "dataType"),
    ALL_COLUMNS((short)5, "allColumns"),
    SHOW_TIMESERIES_LIST((short)6, "showTimeseriesList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STATUS
          return STATUS;
        case 2: // METADATA_IN_JSON
          return METADATA_IN_JSON;
        case 3: // DELTA_OBJECT_MAP
          return DELTA_OBJECT_MAP;
        case 4: // DATA_TYPE
          return DATA_TYPE;
        case 5: // ALL_COLUMNS
          return ALL_COLUMNS;
        case 6: // SHOW_TIMESERIES_LIST
          return SHOW_TIMESERIES_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.METADATA_IN_JSON,_Fields.DELTA_OBJECT_MAP,_Fields.DATA_TYPE,_Fields.ALL_COLUMNS,_Fields.SHOW_TIMESERIES_LIST};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TS_Status.class)));
    tmpMap.put(_Fields.METADATA_IN_JSON, new org.apache.thrift.meta_data.FieldMetaData("metadataInJson", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DELTA_OBJECT_MAP, new org.apache.thrift.meta_data.FieldMetaData("deltaObjectMap", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.DATA_TYPE, new org.apache.thrift.meta_data.FieldMetaData("dataType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ALL_COLUMNS, new org.apache.thrift.meta_data.FieldMetaData("allColumns", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.SHOW_TIMESERIES_LIST, new org.apache.thrift.meta_data.FieldMetaData("showTimeseriesList", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TSFetchMetadataResp.class, metaDataMap);
  }

  public TSFetchMetadataResp() {
  }

  public TSFetchMetadataResp(
    TS_Status status)
  {
    this();
    this.status = status;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TSFetchMetadataResp(TSFetchMetadataResp other) {
    if (other.isSetStatus()) {
      this.status = new TS_Status(other.status);
    }
    if (other.isSetMetadataInJson()) {
      this.metadataInJson = other.metadataInJson;
    }
    if (other.isSetDeltaObjectMap()) {
      Map<String,List<String>> __this__deltaObjectMap = new HashMap<String,List<String>>(other.deltaObjectMap.size());
      for (Map.Entry<String, List<String>> other_element : other.deltaObjectMap.entrySet()) {

        String other_element_key = other_element.getKey();
        List<String> other_element_value = other_element.getValue();

        String __this__deltaObjectMap_copy_key = other_element_key;

        List<String> __this__deltaObjectMap_copy_value = new ArrayList<String>(other_element_value);

        __this__deltaObjectMap.put(__this__deltaObjectMap_copy_key, __this__deltaObjectMap_copy_value);
      }
      this.deltaObjectMap = __this__deltaObjectMap;
    }
    if (other.isSetDataType()) {
      this.dataType = other.dataType;
    }
    if (other.isSetAllColumns()) {
      List<String> __this__allColumns = new ArrayList<String>(other.allColumns);
      this.allColumns = __this__allColumns;
    }
    if (other.isSetShowTimeseriesList()) {
      List<List<String>> __this__showTimeseriesList = new ArrayList<List<String>>(other.showTimeseriesList.size());
      for (List<String> other_element : other.showTimeseriesList) {
        List<String> __this__showTimeseriesList_copy = new ArrayList<String>(other_element);
        __this__showTimeseriesList.add(__this__showTimeseriesList_copy);
      }
      this.showTimeseriesList = __this__showTimeseriesList;
    }
  }

  public TSFetchMetadataResp deepCopy() {
    return new TSFetchMetadataResp(this);
  }

  @Override
  public void clear() {
    this.status = null;
    this.metadataInJson = null;
    this.deltaObjectMap = null;
    this.dataType = null;
    this.allColumns = null;
    this.showTimeseriesList = null;
  }

  public TS_Status getStatus() {
    return this.status;
  }

  public TSFetchMetadataResp setStatus(TS_Status status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public String getMetadataInJson() {
    return this.metadataInJson;
  }

  public TSFetchMetadataResp setMetadataInJson(String metadataInJson) {
    this.metadataInJson = metadataInJson;
    return this;
  }

  public void unsetMetadataInJson() {
    this.metadataInJson = null;
  }

  /** Returns true if field metadataInJson is set (has been assigned a value) and false otherwise */
  public boolean isSetMetadataInJson() {
    return this.metadataInJson != null;
  }

  public void setMetadataInJsonIsSet(boolean value) {
    if (!value) {
      this.metadataInJson = null;
    }
  }

  public int getDeltaObjectMapSize() {
    return (this.deltaObjectMap == null) ? 0 : this.deltaObjectMap.size();
  }

  public void putToDeltaObjectMap(String key, List<String> val) {
    if (this.deltaObjectMap == null) {
      this.deltaObjectMap = new HashMap<String,List<String>>();
    }
    this.deltaObjectMap.put(key, val);
  }

  public Map<String,List<String>> getDeltaObjectMap() {
    return this.deltaObjectMap;
  }

  public TSFetchMetadataResp setDeltaObjectMap(Map<String,List<String>> deltaObjectMap) {
    this.deltaObjectMap = deltaObjectMap;
    return this;
  }

  public void unsetDeltaObjectMap() {
    this.deltaObjectMap = null;
  }

  /** Returns true if field deltaObjectMap is set (has been assigned a value) and false otherwise */
  public boolean isSetDeltaObjectMap() {
    return this.deltaObjectMap != null;
  }

  public void setDeltaObjectMapIsSet(boolean value) {
    if (!value) {
      this.deltaObjectMap = null;
    }
  }

  public String getDataType() {
    return this.dataType;
  }

  public TSFetchMetadataResp setDataType(String dataType) {
    this.dataType = dataType;
    return this;
  }

  public void unsetDataType() {
    this.dataType = null;
  }

  /** Returns true if field dataType is set (has been assigned a value) and false otherwise */
  public boolean isSetDataType() {
    return this.dataType != null;
  }

  public void setDataTypeIsSet(boolean value) {
    if (!value) {
      this.dataType = null;
    }
  }

  public int getAllColumnsSize() {
    return (this.allColumns == null) ? 0 : this.allColumns.size();
  }

  public java.util.Iterator<String> getAllColumnsIterator() {
    return (this.allColumns == null) ? null : this.allColumns.iterator();
  }

  public void addToAllColumns(String elem) {
    if (this.allColumns == null) {
      this.allColumns = new ArrayList<String>();
    }
    this.allColumns.add(elem);
  }

  public List<String> getAllColumns() {
    return this.allColumns;
  }

  public TSFetchMetadataResp setAllColumns(List<String> allColumns) {
    this.allColumns = allColumns;
    return this;
  }

  public void unsetAllColumns() {
    this.allColumns = null;
  }

  /** Returns true if field allColumns is set (has been assigned a value) and false otherwise */
  public boolean isSetAllColumns() {
    return this.allColumns != null;
  }

  public void setAllColumnsIsSet(boolean value) {
    if (!value) {
      this.allColumns = null;
    }
  }

  public int getShowTimeseriesListSize() {
    return (this.showTimeseriesList == null) ? 0 : this.showTimeseriesList.size();
  }

  public java.util.Iterator<List<String>> getShowTimeseriesListIterator() {
    return (this.showTimeseriesList == null) ? null : this.showTimeseriesList.iterator();
  }

  public void addToShowTimeseriesList(List<String> elem) {
    if (this.showTimeseriesList == null) {
      this.showTimeseriesList = new ArrayList<List<String>>();
    }
    this.showTimeseriesList.add(elem);
  }

  public List<List<String>> getShowTimeseriesList() {
    return this.showTimeseriesList;
  }

  public TSFetchMetadataResp setShowTimeseriesList(List<List<String>> showTimeseriesList) {
    this.showTimeseriesList = showTimeseriesList;
    return this;
  }

  public void unsetShowTimeseriesList() {
    this.showTimeseriesList = null;
  }

  /** Returns true if field showTimeseriesList is set (has been assigned a value) and false otherwise */
  public boolean isSetShowTimeseriesList() {
    return this.showTimeseriesList != null;
  }

  public void setShowTimeseriesListIsSet(boolean value) {
    if (!value) {
      this.showTimeseriesList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((TS_Status)value);
      }
      break;

    case METADATA_IN_JSON:
      if (value == null) {
        unsetMetadataInJson();
      } else {
        setMetadataInJson((String)value);
      }
      break;

    case DELTA_OBJECT_MAP:
      if (value == null) {
        unsetDeltaObjectMap();
      } else {
        setDeltaObjectMap((Map<String,List<String>>)value);
      }
      break;

    case DATA_TYPE:
      if (value == null) {
        unsetDataType();
      } else {
        setDataType((String)value);
      }
      break;

    case ALL_COLUMNS:
      if (value == null) {
        unsetAllColumns();
      } else {
        setAllColumns((List<String>)value);
      }
      break;

    case SHOW_TIMESERIES_LIST:
      if (value == null) {
        unsetShowTimeseriesList();
      } else {
        setShowTimeseriesList((List<List<String>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STATUS:
      return getStatus();

    case METADATA_IN_JSON:
      return getMetadataInJson();

    case DELTA_OBJECT_MAP:
      return getDeltaObjectMap();

    case DATA_TYPE:
      return getDataType();

    case ALL_COLUMNS:
      return getAllColumns();

    case SHOW_TIMESERIES_LIST:
      return getShowTimeseriesList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STATUS:
      return isSetStatus();
    case METADATA_IN_JSON:
      return isSetMetadataInJson();
    case DELTA_OBJECT_MAP:
      return isSetDeltaObjectMap();
    case DATA_TYPE:
      return isSetDataType();
    case ALL_COLUMNS:
      return isSetAllColumns();
    case SHOW_TIMESERIES_LIST:
      return isSetShowTimeseriesList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TSFetchMetadataResp)
      return this.equals((TSFetchMetadataResp)that);
    return false;
  }

  public boolean equals(TSFetchMetadataResp that) {
    if (that == null)
      return false;

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_metadataInJson = true && this.isSetMetadataInJson();
    boolean that_present_metadataInJson = true && that.isSetMetadataInJson();
    if (this_present_metadataInJson || that_present_metadataInJson) {
      if (!(this_present_metadataInJson && that_present_metadataInJson))
        return false;
      if (!this.metadataInJson.equals(that.metadataInJson))
        return false;
    }

    boolean this_present_deltaObjectMap = true && this.isSetDeltaObjectMap();
    boolean that_present_deltaObjectMap = true && that.isSetDeltaObjectMap();
    if (this_present_deltaObjectMap || that_present_deltaObjectMap) {
      if (!(this_present_deltaObjectMap && that_present_deltaObjectMap))
        return false;
      if (!this.deltaObjectMap.equals(that.deltaObjectMap))
        return false;
    }

    boolean this_present_dataType = true && this.isSetDataType();
    boolean that_present_dataType = true && that.isSetDataType();
    if (this_present_dataType || that_present_dataType) {
      if (!(this_present_dataType && that_present_dataType))
        return false;
      if (!this.dataType.equals(that.dataType))
        return false;
    }

    boolean this_present_allColumns = true && this.isSetAllColumns();
    boolean that_present_allColumns = true && that.isSetAllColumns();
    if (this_present_allColumns || that_present_allColumns) {
      if (!(this_present_allColumns && that_present_allColumns))
        return false;
      if (!this.allColumns.equals(that.allColumns))
        return false;
    }

    boolean this_present_showTimeseriesList = true && this.isSetShowTimeseriesList();
    boolean that_present_showTimeseriesList = true && that.isSetShowTimeseriesList();
    if (this_present_showTimeseriesList || that_present_showTimeseriesList) {
      if (!(this_present_showTimeseriesList && that_present_showTimeseriesList))
        return false;
      if (!this.showTimeseriesList.equals(that.showTimeseriesList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TSFetchMetadataResp other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMetadataInJson()).compareTo(other.isSetMetadataInJson());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetadataInJson()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metadataInJson, other.metadataInJson);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDeltaObjectMap()).compareTo(other.isSetDeltaObjectMap());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeltaObjectMap()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deltaObjectMap, other.deltaObjectMap);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDataType()).compareTo(other.isSetDataType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDataType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dataType, other.dataType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAllColumns()).compareTo(other.isSetAllColumns());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAllColumns()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.allColumns, other.allColumns);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetShowTimeseriesList()).compareTo(other.isSetShowTimeseriesList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetShowTimeseriesList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.showTimeseriesList, other.showTimeseriesList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TSFetchMetadataResp(");
    boolean first = true;

    sb.append("status:");
    if (this.status == null) {
      sb.append("null");
    } else {
      sb.append(this.status);
    }
    first = false;
    if (isSetMetadataInJson()) {
      if (!first) sb.append(", ");
      sb.append("metadataInJson:");
      if (this.metadataInJson == null) {
        sb.append("null");
      } else {
        sb.append(this.metadataInJson);
      }
      first = false;
    }
    if (isSetDeltaObjectMap()) {
      if (!first) sb.append(", ");
      sb.append("deltaObjectMap:");
      if (this.deltaObjectMap == null) {
        sb.append("null");
      } else {
        sb.append(this.deltaObjectMap);
      }
      first = false;
    }
    if (isSetDataType()) {
      if (!first) sb.append(", ");
      sb.append("dataType:");
      if (this.dataType == null) {
        sb.append("null");
      } else {
        sb.append(this.dataType);
      }
      first = false;
    }
    if (isSetAllColumns()) {
      if (!first) sb.append(", ");
      sb.append("allColumns:");
      if (this.allColumns == null) {
        sb.append("null");
      } else {
        sb.append(this.allColumns);
      }
      first = false;
    }
    if (isSetShowTimeseriesList()) {
      if (!first) sb.append(", ");
      sb.append("showTimeseriesList:");
      if (this.showTimeseriesList == null) {
        sb.append("null");
      } else {
        sb.append(this.showTimeseriesList);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (status == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'status' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (status != null) {
      status.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TSFetchMetadataRespStandardSchemeFactory implements SchemeFactory {
    public TSFetchMetadataRespStandardScheme getScheme() {
      return new TSFetchMetadataRespStandardScheme();
    }
  }

  private static class TSFetchMetadataRespStandardScheme extends StandardScheme<TSFetchMetadataResp> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TSFetchMetadataResp struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.status = new TS_Status();
              struct.status.read(iprot);
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // METADATA_IN_JSON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.metadataInJson = iprot.readString();
              struct.setMetadataInJsonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DELTA_OBJECT_MAP
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map132 = iprot.readMapBegin();
                struct.deltaObjectMap = new HashMap<String,List<String>>(2*_map132.size);
                for (int _i133 = 0; _i133 < _map132.size; ++_i133)
                {
                  String _key134;
                  List<String> _val135;
                  _key134 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TList _list136 = iprot.readListBegin();
                    _val135 = new ArrayList<String>(_list136.size);
                    for (int _i137 = 0; _i137 < _list136.size; ++_i137)
                    {
                      String _elem138;
                      _elem138 = iprot.readString();
                      _val135.add(_elem138);
                    }
                    iprot.readListEnd();
                  }
                  struct.deltaObjectMap.put(_key134, _val135);
                }
                iprot.readMapEnd();
              }
              struct.setDeltaObjectMapIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // DATA_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dataType = iprot.readString();
              struct.setDataTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ALL_COLUMNS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list139 = iprot.readListBegin();
                struct.allColumns = new ArrayList<String>(_list139.size);
                for (int _i140 = 0; _i140 < _list139.size; ++_i140)
                {
                  String _elem141;
                  _elem141 = iprot.readString();
                  struct.allColumns.add(_elem141);
                }
                iprot.readListEnd();
              }
              struct.setAllColumnsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // SHOW_TIMESERIES_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list142 = iprot.readListBegin();
                struct.showTimeseriesList = new ArrayList<List<String>>(_list142.size);
                for (int _i143 = 0; _i143 < _list142.size; ++_i143)
                {
                  List<String> _elem144;
                  {
                    org.apache.thrift.protocol.TList _list145 = iprot.readListBegin();
                    _elem144 = new ArrayList<String>(_list145.size);
                    for (int _i146 = 0; _i146 < _list145.size; ++_i146)
                    {
                      String _elem147;
                      _elem147 = iprot.readString();
                      _elem144.add(_elem147);
                    }
                    iprot.readListEnd();
                  }
                  struct.showTimeseriesList.add(_elem144);
                }
                iprot.readListEnd();
              }
              struct.setShowTimeseriesListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TSFetchMetadataResp struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.status != null) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        struct.status.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.metadataInJson != null) {
        if (struct.isSetMetadataInJson()) {
          oprot.writeFieldBegin(METADATA_IN_JSON_FIELD_DESC);
          oprot.writeString(struct.metadataInJson);
          oprot.writeFieldEnd();
        }
      }
      if (struct.deltaObjectMap != null) {
        if (struct.isSetDeltaObjectMap()) {
          oprot.writeFieldBegin(DELTA_OBJECT_MAP_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.LIST, struct.deltaObjectMap.size()));
            for (Map.Entry<String, List<String>> _iter148 : struct.deltaObjectMap.entrySet())
            {
              oprot.writeString(_iter148.getKey());
              {
                oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter148.getValue().size()));
                for (String _iter149 : _iter148.getValue())
                {
                  oprot.writeString(_iter149);
                }
                oprot.writeListEnd();
              }
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.dataType != null) {
        if (struct.isSetDataType()) {
          oprot.writeFieldBegin(DATA_TYPE_FIELD_DESC);
          oprot.writeString(struct.dataType);
          oprot.writeFieldEnd();
        }
      }
      if (struct.allColumns != null) {
        if (struct.isSetAllColumns()) {
          oprot.writeFieldBegin(ALL_COLUMNS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.allColumns.size()));
            for (String _iter150 : struct.allColumns)
            {
              oprot.writeString(_iter150);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.showTimeseriesList != null) {
        if (struct.isSetShowTimeseriesList()) {
          oprot.writeFieldBegin(SHOW_TIMESERIES_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.showTimeseriesList.size()));
            for (List<String> _iter151 : struct.showTimeseriesList)
            {
              {
                oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter151.size()));
                for (String _iter152 : _iter151)
                {
                  oprot.writeString(_iter152);
                }
                oprot.writeListEnd();
              }
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TSFetchMetadataRespTupleSchemeFactory implements SchemeFactory {
    public TSFetchMetadataRespTupleScheme getScheme() {
      return new TSFetchMetadataRespTupleScheme();
    }
  }

  private static class TSFetchMetadataRespTupleScheme extends TupleScheme<TSFetchMetadataResp> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TSFetchMetadataResp struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.status.write(oprot);
      BitSet optionals = new BitSet();
      if (struct.isSetMetadataInJson()) {
        optionals.set(0);
      }
      if (struct.isSetDeltaObjectMap()) {
        optionals.set(1);
      }
      if (struct.isSetDataType()) {
        optionals.set(2);
      }
      if (struct.isSetAllColumns()) {
        optionals.set(3);
      }
      if (struct.isSetShowTimeseriesList()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetMetadataInJson()) {
        oprot.writeString(struct.metadataInJson);
      }
      if (struct.isSetDeltaObjectMap()) {
        {
          oprot.writeI32(struct.deltaObjectMap.size());
          for (Map.Entry<String, List<String>> _iter153 : struct.deltaObjectMap.entrySet())
          {
            oprot.writeString(_iter153.getKey());
            {
              oprot.writeI32(_iter153.getValue().size());
              for (String _iter154 : _iter153.getValue())
              {
                oprot.writeString(_iter154);
              }
            }
          }
        }
      }
      if (struct.isSetDataType()) {
        oprot.writeString(struct.dataType);
      }
      if (struct.isSetAllColumns()) {
        {
          oprot.writeI32(struct.allColumns.size());
          for (String _iter155 : struct.allColumns)
          {
            oprot.writeString(_iter155);
          }
        }
      }
      if (struct.isSetShowTimeseriesList()) {
        {
          oprot.writeI32(struct.showTimeseriesList.size());
          for (List<String> _iter156 : struct.showTimeseriesList)
          {
            {
              oprot.writeI32(_iter156.size());
              for (String _iter157 : _iter156)
              {
                oprot.writeString(_iter157);
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TSFetchMetadataResp struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.status = new TS_Status();
      struct.status.read(iprot);
      struct.setStatusIsSet(true);
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.metadataInJson = iprot.readString();
        struct.setMetadataInJsonIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map158 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.deltaObjectMap = new HashMap<String,List<String>>(2*_map158.size);
          for (int _i159 = 0; _i159 < _map158.size; ++_i159)
          {
            String _key160;
            List<String> _val161;
            _key160 = iprot.readString();
            {
              org.apache.thrift.protocol.TList _list162 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _val161 = new ArrayList<String>(_list162.size);
              for (int _i163 = 0; _i163 < _list162.size; ++_i163)
              {
                String _elem164;
                _elem164 = iprot.readString();
                _val161.add(_elem164);
              }
            }
            struct.deltaObjectMap.put(_key160, _val161);
          }
        }
        struct.setDeltaObjectMapIsSet(true);
      }
      if (incoming.get(2)) {
        struct.dataType = iprot.readString();
        struct.setDataTypeIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list165 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.allColumns = new ArrayList<String>(_list165.size);
          for (int _i166 = 0; _i166 < _list165.size; ++_i166)
          {
            String _elem167;
            _elem167 = iprot.readString();
            struct.allColumns.add(_elem167);
          }
        }
        struct.setAllColumnsIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list168 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.showTimeseriesList = new ArrayList<List<String>>(_list168.size);
          for (int _i169 = 0; _i169 < _list168.size; ++_i169)
          {
            List<String> _elem170;
            {
              org.apache.thrift.protocol.TList _list171 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem170 = new ArrayList<String>(_list171.size);
              for (int _i172 = 0; _i172 < _list171.size; ++_i172)
              {
                String _elem173;
                _elem173 = iprot.readString();
                _elem170.add(_elem173);
              }
            }
            struct.showTimeseriesList.add(_elem170);
          }
        }
        struct.setShowTimeseriesListIsSet(true);
      }
    }
  }

}

